---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
  labels:
    app: micro
spec:
  replicas: 1
  selector:
    matchLabels:
      pod-label: users-api-prod
  template:
    metadata:
      labels:
        pod-label: users-api-prod
    spec:
      containers:
        - name: users-api
          image: ghcr.io/keinercx/users-api:1.0
          env:
            - name: DATABASE_URL
              configMapKeyRef:
              name: database-creds
              key: DATABASE_URL
          ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: users-api
  labels:
    app: micro
spec:
  selector:
    pod-label: users-api-prod
  ports:
    - protocol: TCP
      port: 3000
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: users-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`micro.keiner.lol`) && PathPrefix(`/api/users`)
      services:
        - name: users-api
          port: 3000
      middlewares:
      - name: users-api-replacepath
---
# Replace the path with /foo
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: users-api-replacepath
spec:
  stripPrefix:
    prefixes:
      - /api/users