FROM node:18
LABEL org.opencontainers.image.source="https://github.com/keinercx/Micro-Web.git"

# Create Directory for the Container
WORKDIR /usr/src/app
# Only copy the package.json file to work directory
COPY ./apps/beta_access/package.json .
COPY ./apps/beta_access/tsconfig.json .
COPY ./prisma .
# Install all Packages
RUN npm install
RUN npx prisma generate
# Copy all other source code to work directory
ADD ./apps/beta_access/src /usr/src/app

# TypeScript
RUN npx tsc

# Start
CMD [ "npm", "start" ]
EXPOSE 3000