name: publish

on:
  push:
    # # Pattern matched against refs/tags
    # tags:
    #   - "v[0-9]+.[0-9]+"
jobs:
  publish-api-images:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Changed files
        uses: tj-actions/changed-files@v9
        id: changed-files
        with:
          files: |
             apps/users
             apps/beta_access
             apps/web
      
      - name: Build the Users API
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          docker build --tag ghcr.io/keinercx/microservices/users-api:$GITHUB_SHA -f dockerfiles/Dockerfile_users .
          docker push ghcr.io/keinercx/microservices/users-api:$GITHUB_SHA

      - name: Build the Beta Acces API
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          docker build --tag ghcr.io/keinercx/microservices/beta-access-api:$GITHUB_SHA -f dockerfiles/Dockerfile_beta .
          docker push ghcr.io/keinercx/microservices/beta-access-api:$GITHUB_SHA

      - name: Build the Website
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          docker build --tag ghcr.io/keinercx/microservices/website:$GITHUB_SHA -f dockerfiles/Dockerfile_web .
          docker push ghcr.io/keinercx/microservices/website:$GITHUB_SHA
